version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: matchmood_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: matchmood
      POSTGRES_PASSWORD: matchmood
      POSTGRES_DB: matchmood
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
